# AI Memory Service Configuration
# Uses environment variables for sensitive data (see .env file)

[server]
host = "127.0.0.1"
port = 8080
workers = 4
environment = "development"
cors_origins = ["http://localhost:3000", "http://127.0.0.1:8888"]

[storage]
neo4j_uri = "bolt://localhost:7687"
neo4j_user = "neo4j"
# Password loaded from NEO4J_PASSWORD environment variable
neo4j_password = ""
connection_pool_size = 16

[embedding]
model_path = "./models/embeddinggemma-300m"
tokenizer_path = "./models/embeddinggemma-300m/tokenizer.json"
batch_size = 128
max_sequence_length = 2048
# embedding_dimension is set via Option<usize> in code defaults
# Critical for proper vector similarity
normalize_embeddings = true
# Use float32 for best compatibility
precision = "float32"
# Enable specialized prompts for better quality
use_specialized_prompts = true

[cache]
l1_size = 1000
l2_size = 10000
ttl_seconds = 3600
compression_enabled = true

[brain]
max_memories = 100000
importance_threshold = 0.1
consolidation_interval = 300
decay_rate = 0.01

